'use strict';

/**
 * Babel plugin: rewrite `<pkg>/lib` subpath imports to `<pkg>/es`.
 *
 * Use case: a component library authored against `antd/lib/xxx` (either
 * directly in source or generated by `babel-plugin-import`) needs its ESM
 * build to consume `antd/es/xxx` instead, so that bundlers resolve a single
 * ES module graph (and therefore a single React context) for antd and rc-*.
 *
 * By default the rewrite applies to ANY package, following the plugin's
 * namesake convention (lib → es). Packages whose `es` layout does not exist
 * (e.g. `lodash/lib`) will fail loudly at module-resolution time; add them
 * to `exclude` to keep their paths untouched.
 *
 * The rewrite runs on `Program.exit` so it also sees import declarations
 * generated by other plugins earlier in the pipeline (notably
 * `babel-plugin-import`, which expands `import { Button } from 'antd'` into
 * `antd/lib/button` imports on its own `Program.exit`).
 *
 * Options:
 *   exclude: Array<string | RegExp> — package names to leave untouched.
 *   include: Array<string | RegExp> — if provided, ONLY these package names
 *            are rewritten (strict mode; takes precedence over `exclude`).
 */

// Matches `<pkg>/lib` or `<pkg>/lib/<subpath>`, capturing the package name
// (scope-aware: `@scope/name/lib/...` captures `@scope/name`).
const LIB_PATH_RE = /^((?:@[\w.-]+\/)?[\w.-]+)\/lib(?=\/|$)/;

function matches(matcher, pkg) {
  return typeof matcher === 'string' ? matcher === pkg : matcher.test(pkg);
}

function toEsSource(source, opts) {
  const match = source.match(LIB_PATH_RE);
  if (!match) return null;

  const pkg = match[1];
  const { include, exclude } = opts;
  if (include && !include.some((matcher) => matches(matcher, pkg))) return null;
  if (exclude && exclude.some((matcher) => matches(matcher, pkg))) return null;

  return source.replace(LIB_PATH_RE, '$1/es');
}

module.exports = function babelPluginImportLibToEs({ types: t }) {
  return {
    name: 'babel-plugin-import-lib-to-es',
    visitor: {
      Program: {
        exit(programPath, state) {
          const opts = state.opts || {};

          function rewriteSource(sourceNode) {
            const rewritten = toEsSource(sourceNode.value, opts);
            if (rewritten) sourceNode.value = rewritten;
          }

          programPath.traverse({
            ImportDeclaration(path) {
              rewriteSource(path.node.source);
            },
            ExportNamedDeclaration(path) {
              if (path.node.source) rewriteSource(path.node.source);
            },
            ExportAllDeclaration(path) {
              rewriteSource(path.node.source);
            },
            CallExpression(path) {
              const { callee, arguments: args } = path.node;
              // bare require('...') and dynamic import('...')
              const isRewritable = t.isIdentifier(callee, { name: 'require' }) || t.isImport(callee);
              if (isRewritable && args.length === 1 && t.isStringLiteral(args[0])) {
                rewriteSource(args[0]);
              }
            },
          });
        },
      },
    },
  };
};
